### ISSUE TITLE
Add class name prefixes to fix potential style leaks

### ISSUE THREAD

**Issue by rbrtsmith** [JSainsburyPLC/react-timelines#29]
As it currently stands we are not prefixing our classNames e.g. we have `.sidebar`
which means consumers CSS is likely to leak into the timeline.

I suggest we prefix all our classNames with `rt-` to avoid this.

**Comment by WebSeed** [comment]
We have `.react-timelines` wrapper which adds some level of protection but agree there is still likely to be some leakage.

Something like `.rt` or `.rtl` would help at the expense of readability / noise in the code-base. Would also not guarantee working okay e.g. users can just style `p` directly and there isn't much we can do about this.
