### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by nadeemja** [JSainsburyPLC/react-timelines#40]
Hi,

Would you mind demoing this inside a storybook? 

https://storybooks.js.org/

**Comment by rbrtsmith** [comment]
Producing a demo is something we intend to do in the coming weeks.  Thanks for bringing it to our attention :smile:

**Comment by WebSeed** [comment]
Hi, we now have a simple demo at https://jsainsburyplc.github.io/react-timelines/

Will look at documentation next (and storybook-like configuration options on the demo)
